blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('article/<slug>/', views.article_detail, name='article_detail'),
    path('article/<slug>/edit', views.update_article, name='update_article'),
    path('article_new/', views.create_article, name='create_article'),
    path('article/<slug>/like/', views.like_article, name='like_article'),
    path('article/<slug>/share/', views.share_article, name='share_article'),
    path('trending/', views.trending_articles, name='trending_articles'),
    path('recent/', views.recent_articles, name='recent_articles'),
    path('article/<slug>/comment/<int:comment_id>/reply/', views.post_reply, name='post_reply'),

    # URL for loading comments via AJAX
    path('article/<slug:slug>/comments/', views.load_comments, name='load_comments'),
    
    # URL for posting a comment via AJAX
    path('article/<slug:slug>/post-comment/', views.post_comment, name='post_comment'),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search_articles, name='search_articles'),    
    path('aboutus', views.aboutus, name='aboutus'),
    path('contactus', views.contactus, name='contactus'),
    path('whatweoffer', views.wwo, name='wwo'),
    path('faq', views.faq, name='faq'),
    path('termsandconditions', views.tandc, name='tandc'), 
    path('blog_mgmt', views.blog_mgmt, name='blog_mgmt'),
    path('ccg', views.ccg, name='ccg'),

    #### resources URL's ####
    path('ai_home', views.ai_home, name='ai_home'),
    path('ai_learn', views.ai_learn, name='ai_learn'),
    path('ai_p_t', views.ai_projects, name='ai_projects'),
    path('ai_resources', views.ai_resources, name='ai_resources'),
    path('ai_c_s', views.ai_c_s, name='ai_c_s'),
    path('ai_test', views.ai_test, name='ai_test'),
    path('ai_blogs', views.ai_blogs, name='ai_blogs'),

    path('icArticle', views.icArticle, name='icArticle'),
    path('saArticle', views.saArticle, name='saArticle'),        
    path('larsArticle', views.larsArticle, name='larsArticle'),
    path('lpaArticle', views.lpaArticle, name='lpaArticle'),
    path('lavArticle', views.lavArticle, name='lavArticle'),
    path('chatbotsArticle', views.chatbotsArticle, name='chatbotsArticle'),
    path('tnfArticle', views.tnfArticle, name='tnfArticle'),
    path('code_repoArticle', views.code_repoArticle, name='code_repoArticle'),  
    path('ml', views.ml, name='ml'),
    path('dl', views.dl, name='dl'),
    path('nlp', views.nlp, name='nlp'),
    path('cv', views.cv, name='cv'),   
    path('ai_tutorials', views.ai_tutorials, name='ai_tutorials'),          
    path("chatbot/", views.chatbot_response, name="chatbot"),
    path("chat/", views.chat, name="chat"),

    path("robots.txt", views.RobotsTxtView.as_view(content_type="text/plain"), name="robots"),
    path("ads.txt", views.adsTxtView.as_view(content_type="text/plain"), name="ads"),
]

ikSite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from dashboard.views import pages_error_404

handler404 = pages_error_404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('blog.urls')),
    path('', include('subscriptions.urls')),
    path('', include('resources.urls')),
    path('accounts/', include('users.urls')),
    #path('google_site_verf/', google_site_verf),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/update/', views.profile_update, name='profile'),
    path('logout/', views.logout, name='logout'),

    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    
    path('changepass', views.user_changepass, name="changepass"),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('password_reset/done/', views.password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete, name='password_reset_complete'),
    path('password_reset/invalid/', views.password_reset_invalid, name='password_reset_invalid'),    

]

dashboard/models.py
from django.db import models

dashboard/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, required=False, label='Search by title')

dashboard/views.py
from django.shortcuts import render
import requests
from bs4 import BeautifulSoup

from django.core.mail import EmailMessage
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods
from blog.models import Article, Comment, Share
from resources.models import Resource,Chapter
from blog.forms import ArticleForm, CommentForm, ReplyForm
from .forms import SearchForm
from django.db import models
from django.db.models import Count
from django.contrib.auth.decorators import user_passes_test
from subscriptions.models import UserSubscription


# Create your views here.

# views.py

from django.shortcuts import render
from django.http import HttpResponse
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.db.models import Q

def upload_file(request):
    if request.method == 'POST' and request.FILES:
        file = request.FILES['file']
        file_name = file.name
        file_content = file.read()
        file_path = default_storage.save(file_name, ContentFile(file_content))
        return HttpResponse(f'File uploaded to: {file_path}')
    return render(request, 'upload.html')

def search_articles(request):
    form = SearchForm(request.GET or None)
    articles = Article.objects.all()
    resources = Resource.objects.all()

    if form.is_valid():
        query = form.cleaned_data.get('query')
        if query:
            articles = articles.filter(title__icontains=query)
            resources = resources.filter(title__icontains=query)

    return render(request, 'dashboard/components/search_results.html', {'form': form, 'articles': articles,"resources":resources})

def home(request):


    articles = Article.objects.all().order_by('-created_at')[:10]
    t_articles = Article.objects.annotate(num_likes=models.Count('likes')).order_by('-num_likes')    
    r_articles = Article.objects.all().order_by('-created_at')[:5]
    return render(request,'dashboard/home.html',{'articles': articles, 't_articles': t_articles,'r_articles': r_articles})   

def contactus(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        # Validate form data (basic validation)
        if not all([name, email, subject, message]):
            return render(request, 'pages/contactus.html', {'error': 'All fields are required.'})

        # Prepare email
        email_subject = f"Contact Form Submission: {subject}"
        email_message = f"Name: {name}\nEmail: {email}\n\nMessage:\n{message}"
        from_email = settings.DEFAULT_FROM_EMAIL
        from_name = "ikSaan.com"
        from_email_with_name = f"{from_name} <{from_email}>"
        recipient_list = [settings.DEFAULT_FROM_EMAIL]  # Adjust to the desired recipient(s)

        # Send email
        try:
            send_mail(email_subject, email_message, from_email_with_name, recipient_list, fail_silently=False)
            return render(request, 'pages/contactus.html', {'sent_message': 'Your message has been sent. Thank you!'})
        except Exception as e:
            print(f"Error sending email: {e}")
            return render(request, 'pages/contactus.html', {'error': 'There was an error sending your message. Please try again later.'})

    else:
        return render(request, 'pages/contactus.html')  

def wwo(request):
    return render(request, 'pages/whatweoffer.html')
    
def aboutus(request):
    return render(request, 'pages/aboutus.html')   

def faq(request):
    return render(request, 'pages/pages_faq.html')    

def tandc(request):
    return render(request, 'pages/terms_conditions.html')  

def ccg(request):
    return render(request,'pages/ccg.html')     


def ai_test(request):
    return render(request,'pages/ai_test.html')    

from django.views.generic import TemplateView


class RobotsTxtView(TemplateView):
    template_name = "robots.txt"


class adsTxtView(TemplateView):
    template_name = "ads.txt"
    
##########################
######## Mgmt ############

@user_passes_test(lambda u: u.is_superuser)
def blog_mgmt(request):
    articles = Article.objects.all()
    comments = Comment.objects.all()

    if request.method == 'POST':
        if 'approve_article' in request.POST:
            article_id = request.POST.get('article_id')
            article = get_object_or_404(Article, id=article_id)
            article.is_approved = True
            article.save()
        elif 'disapprove_article' in request.POST:
            article_id = request.POST.get('article_id')
            article = get_object_or_404(Article, id=article_id)
            article.is_approved = False
            article.save()
        elif 'approve_comment' in request.POST:
            comment_id = request.POST.get('comment_id')
            comment = get_object_or_404(Comment, id=comment_id)
            comment.is_approved = True
            comment.save()
        elif 'disapprove_comment' in request.POST:
            comment_id = request.POST.get('comment_id')
            comment = get_object_or_404(Comment, id=comment_id)
            comment.is_approved = False
            comment.save()
        elif 'delete_article' in request.POST:
            article_id = request.POST.get('article_id')
            article = get_object_or_404(Article, id=article_id)
            article.delete()
        elif 'delete_comment' in request.POST:
            comment_id = request.POST.get('comment_id')
            comment = get_object_or_404(Comment, id=comment_id)
            comment.delete()
        elif 'create_article' in request.POST:
            form = ArticleForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('blog_mgmt')
        elif 'update_article' in request.POST:
            article_id = request.POST.get('article_id')
            article = get_object_or_404(Article, id=article_id)
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('blog_mgmt')

    article_form = ArticleForm()
    return render(request, 'mgmt/blog_mgmt.html', {
        'articles': articles,
        'comments': comments,
        'article_form': article_form,
    })   


    ##############################################################
    ############          Resources Pages             ############
    ##############################################################

def pages_error_404(request,exception=None):
    return render(request,'pages/pages_error_404.html', status=404)


def ai_home(request):
    return render(request,'r/ai_home/ai_home.html')
def ai_learn(request):
    return render(request,'r/ai_learn/ai_learn.html')
def ai_projects(request):
    icArticle = Article.objects.filter(title="Image Classification")
    saArticle = Article.objects.filter(title="Sentiment Analysis")
    larsArticle = Article.objects.filter(title="Learn AI Recommendation Systems")
    lpaArticle = Article.objects.filter(title="Learn Predictive Analytics")
    lavArticle = Article.objects.filter(title="Learn Autonomous Vehicles")
    context={
        'ic':icArticle,
        'sa':saArticle,
        'lars':larsArticle,
        'lpa':lpaArticle,
        'lav':lavArticle,
    }
    return render(request,'r/ai_projects/ai_projects.html',{"context":context})
def ai_resources(request):
    return render(request,'r/ai_resources/ai_resources.html')
def ai_c_s(request):
    return render(request,'r/ai_c_s/ai_c_s.html')
def ai_blogs(request):
    return render(request,'r/ai_blogs/ai_blogs.html')     
def icArticle(request):
    return render(request,'r/ai_pages/ic.html')                                           
def saArticle(request):
    return render(request,'r/ai_pages/sa.html')
def larsArticle(request):
    return render(request,'r/ai_pages/lars.html')
def lpaArticle(request):
    return render(request,'r/ai_pages/lpa.html')
def lavArticle(request):
    return render(request,'r/ai_pages/lav.html')  
def chatbotsArticle(request):
    return render(request,'r/ai_pages/chatbots.html')    

def tnfArticle(request):
    return render(request,'r/ai_pages/tnf.html')  
def code_repoArticle(request):
    return render(request,'r/ai_pages/code_repo.html')   

def ml(request):
    return render(request,'r/ai_pages/ml.html')  
def dl(request):
    return render(request,'r/ai_pages/dl.html')   
def nlp(request):
    return render(request,'r/ai_pages/nlp.html')  
def cv(request):
    return render(request,'r/ai_pages/cv.html')
def ai_tutorials(request):
    return render(request,'r/ai_projects/ai_tutorials.html')   


"""
def google_site_verf():
    return render_template("dashboard/google-provided.html")                              
"""

import requests
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def chatbot_response(request):
    if request.method == "POST":
        body = json.loads(request.body.decode("utf-8"))
        user_message = body.get("message")
        sender_id = body.get("sender")

        if not user_message:
            return JsonResponse({"error": "Message is required"}, status=400)

        # Forward the message to the Rasa server
        rasa_url = "http://13.234.118.53:5005/webhooks/rest/webhook"
        response = requests.post(rasa_url, json={"sender": sender_id, "message": user_message})

        if response.status_code == 200:
            rasa_response = response.json()
            return JsonResponse({"messages": rasa_response}, safe=False)
        else:
            return JsonResponse({"error": "Error connecting to Rasa"}, status=response.status_code)

    return JsonResponse({"error": "Invalid request method"}, status=400)


"""
import requests

templates/dashboard/components/footer.html
{% load static %}
    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
          Copyright  © 2024 <strong><span style="color:tomato;">ikSaan.com</span></strong> - The AI Learning HUB. All Rights Reserved.

        </div>
        <div class="copyright">
          <a class="align-items-center" href="{% url 'tandc' %}">Terms and Conditions</a>
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
        </div>
      </footer><!-- End Footer -->
      


      <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i>
      </a>
      <!-- Vendor JS Files -->
      <script src="/static/assets/vendor/apexcharts/apexcharts.min.js"></script>
      <script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script src="/static/assets/vendor/chart.js/chart.umd.js"></script>
      <script src="/static/assets/vendor/echarts/echarts.min.js"></script>
      <script src="/static/assets/vendor/quill/quill.min.js"></script>
      <script src="/static/assets/vendor/simple-datatables/simple-datatables.js"></script>
      <script src="/static/assets/vendor/tinymce/tinymce.min.js"></script>
      <script src="/static/assets/vendor/php-email-form/validate.js"></script>
      <script>
      document.addEventListener('contextmenu', function(e) {
            e.preventDefault();
        });
    </script>
    <script>
      document.addEventListener('copy', function(e) {
          e.preventDefault();
      });
      document.addEventListener('cut', function(e) {
          e.preventDefault();
      });
      document.addEventListener('contextmenu', function(e) {
          e.preventDefault();
      });
  </script>
      <!-- Template Main JS File -->
      <script src="/static/assets/js/main.js"></script>
      <!--
      <script>
        $(document).ready(function(){
          function callFunction(){alert("Load divs");}
        });
        </script>-->

      <!-- ======= Footer ======= -->

templates/dashboard/components/sidebar.html
{% load static %}
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">
  <!--<a class="p-4" href="{%url 'users:register' %}"> -->
  <a class="p-4" href="{%url 'subscription_plans' %}">    
    <button type="button" class="btn btn-danger">Enroll Now</button>
  </a>
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#home-nav" data-bs-toggle="collapse" href="{% url 'ai_home' %}">
        <i class="bi bi-house-fill"></i><span>Home</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="home-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url 'ai_home' %}">
            <i class="bi bi-circle"></i><span>Home</span>
          </a>
        </li>
        {% if user.is_superuser %}
        <li>
          <a href="{% url 'ccg' %}">
            <i class="bi bi-circle"></i><span>Career Counseling and Guidance</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </li><!-- End Home Nav -->   
    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#learnai-nav" data-bs-toggle="collapse" href="{% url 'ai_learn' %}">
        <i class="fas fa-university"></i><span>Learn AI</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="learnai-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url 'ai_learn' %}">
            <i class="bi bi-circle"></i><span>Fundamentals</span>
          </a>
        </li>
        <li>
          <a href="{% url 'ml' %}">
            <i class="bi bi-circle"></i><span>Machine Learning</span>
          </a>
        </li>    
        <li>
          <a href="{% url 'dl' %}">
            <i class="bi bi-circle"></i><span>Deep Learning</span>
          </a>
        </li>   
        <li>
          <a href="{% url 'nlp' %}">
            <i class="bi bi-circle"></i><span>Natural Language Processing</span>
          </a>
        </li>  
        <li>
          <a href="{% url 'cv' %}">
            <i class="bi bi-circle"></i><span>Computer Vision</span>
          </a>
        </li>                               
        
      </ul>
    </li><!-- End Learn AI Nav -->       
    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#project_tutorials-nav" data-bs-toggle="collapse" href="{% url 'ai_projects' %}">
        <i class="bi bi-person-fill-gear"></i><span>Projects and Tutorials</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="project_tutorials-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url 'ai_projects' %}">
            <i class="bi bi-circle"></i><span>Projects</span>
          </a>
        </li>
        <li>
          <a href="{% url 'ai_tutorials' %}">
            <i class="bi bi-circle"></i><span>Tutorials</span>
          </a>
        </li>  
        <!--
        <li>
          <a href="#">
            <i class="bi bi-circle"></i><span>Intermediate Projects</span>
          </a>
        </li>    
        <li>
          <a href="#">
            <i class="bi bi-circle"></i><span>Interactive Tutorials</span>
          </a>
        </li>
        -->                                     
      </ul>
    </li><!-- End Projects and Tutorials Nav -->         
    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#resources-nav" data-bs-toggle="collapse" href="{% url 'ai_resources' %}">
        <i class="bi bi-boxes"></i><span>Resources</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="resources-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url 'resource_list' %}">
            <i class="bi bi-circle"></i><span>Resources</span>
          </a>
        </li>        
        <li>
          <a href="{% url 'ai_resources' %}">
            <i class="bi bi-circle"></i><span>Datasets</span>
          </a>
        </li>
        <li>
          <a href="{% url 'tnfArticle' %}">
            <i class="bi bi-circle"></i><span>Tools and Frameworks</span>
          </a>
        </li>    
        <li>
          <a href="{% url 'code_repoArticle' %}">
            <i class="bi bi-circle"></i><span>Code Repositories</span>
          </a>
        </li>   
        <li></li>
          <a href="{% url 'ai_test' %}">
            <i class="bi bi-circle"></i><span>test</span>
          </a>
        </li>                                          
      </ul>
    </li><!-- End Resources Nav -->       
       
    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#blog-nav" data-bs-toggle="collapse" href="{% url 'ai_blogs' %}">
        <i class="bi bi-postcard-fill"></i><span>Blog</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="blog-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url 'ai_blogs' %}">
            <i class="bi bi-circle"></i><span>Articles</span>
          </a>
        </li>
        <li>
          <a href="#">
            <i class="bi bi-circle"></i><span>Interviews</span>
          </a>
        </li>                                        
      </ul>
    </li><!-- End Blog Nav -->     
    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#aboutus-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-people-fill"></i><span>About Us</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="aboutus-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{%url 'aboutus' %}">
            <i class="bi bi-circle"></i><span>About us</span>
          </a>
        </li>  
        <li>
          <a href="{%url 'contactus' %}">
            <i class="bi bi-circle"></i><span>Contact Information</span>
          </a>
        </li>                                                          
      </ul>
    </li><!-- End About Us Nav -->
    {% if user.is_superuser %}  
    <li class="nav-item">
      <a class="nav-link collapsed" data-bs-target="#admin-nav" data-bs-toggle="collapse" href="#">
        <i class="bi bi-person-fill-lock"></i><span>Admin</span><i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="admin-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
        <li>
          <a href="{% url 'blog_mgmt' %}">
            <i class="bi bi-circle"></i><span>Blog Mgmt</span>
          </a>
        </li> 
        <li>
          <a href="{% url 'tr_list' %}">
            <i class="bi bi-circle"></i><span>tr</span>
          </a>
        </li>             
      </ul>
    </li><!-- End Admin Nav -->
    {% endif %}                          
  </ul>
</aside>
<!-- End Sidebar-->
           

templates/dashboard/components/topbar.html
{% load static %}
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'home' %}" class="logo d-flex align-items-center">
       <img class="rounded-pill"  src="{% static 'assets/img/iksaanLogo.png' %}"  href="{% url 'home' %}" alt="">
      
       <h5 class="d-lg-block card-title" style="color:tomato"; >ikSaan.com </h5>
       
       <!--<span class="d-lg-block" style="color:tomato"; >ikSaan.com</span> -->

      </a>
      
      <i class="bi bi-list toggle-sidebar-btn " ></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="get" action="{% url 'search_articles' %}">
        {% csrf_token %}
        <input type="text" name="query" placeholder="Search" title="Enter search keyword" required>
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->


    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
        <li class="nav-item d-block d-lg-none">

        </li><!-- End Search Icon-->
      {% if user.is_authenticated %}

        <li class="nav-item dropdown pe-3"> 
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <!--<img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle"> -->
            <img src="/media/{{user.avatar}}" alt="Profile" class="rounded-circle" alt="Gold Subscription" width="20" height="20">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.first_name }} {{ user.last_name }}</span>
          </a><!-- End Profile Iamge Icon -->
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{ user.first_name }} {{ user.last_name }}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'users:profile' %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'users:changepass' %}">
                <i class="bi bi-gear"></i>
                <span>Change Password</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'faq' %}">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'users:logout' %}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->
      {% else %}
        <!-- Display content for users who are not logged in -->
  
        <ul class="d-flex align-items-center">



          <li class="nav-item dropdown pe-3">
            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
              <i class="bi bi-grid-3x3-gap-fill h4"></i>
            </a><!-- End Profile Iamge Icon -->
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                <a class="dropdown-item d-flex align-items-center" href="{% url 'users:login' %}">
                  <i class="bi bi-person"></i>
                  <span>Sign in</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>

              <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'users:register' %}">
                  <i class="bi bi-gear"></i>
                  <span>Register</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>

              <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'faq' %}">
                  <i class="bi bi-question-circle"></i>
                  <span>Need Help?</span>
                </a>
              </li>
              <li>
                <hr class="dropdown-divider">
              </li>

            </ul><!-- End Profile Dropdown Items -->
          </li><!-- End Profile Nav -->
        </ul>
      {% endif %}
    </ul>
    </nav><!-- End Icons Navigation -->
  
  </header>
  <!-- End Header -->